// const ADD_MESSAGE = { type: 'ADD_MESSAGE' };
// const SEND_MESSAGE = { type: 'SEND_MESSAGE' };
// const START_FETCHING_MESSAGES = { type: 'START_FETCHING_MESSAGES' };
// const RECEIVED_MESSAGES = { type: 'RECEIVED_MESSAGES' };
const SET_USERNAME = { type: 'SET_USERNAME' };

const actions = {
  // ADD_MESSAGE: ADD_MESSAGE,
  // SEND_MESSAGE: SEND_MESSAGE,
  // START_FETCHING_MESSAGES: START_FETCHING_MESSAGES,
  // RECEIVED_MESSAGES: RECEIVED_MESSAGES,
  SET_USERNAME: SET_USERNAME
}

export default actions;
