module.exports = {
  //loading recipes
  SET_USERNAME: 'SET_USERNAME',
  LOAD_ALL_MESSAGES: 'LOAD_ALL_MESSAGES',
  ADD_NEW_MESSAGE: 'ADD_NEW_MESSAGE',
  CHANGE_MESSAGE_INPUT: 'CHANGE_MESSAGE_INPUT',
  CLEAR_MESSAGE_INPUT: 'CLEAR_MESSAGE_INPUT'
};
