export default = {
  ADD_MESSAGE: 'ADD_MESSAGE',
  SEND_MESSAGE: 'SEND_MESSAGE',
  START_FETCHING_MESSAGES: 'START_FETCHING_MESSAGES',
  RECEIVED_MESSAGES: 'RECEIVED_MESSAGES',
  SET_USERNAME: 'SET_USERNAME'
};
